{
    "name": "Hospital Management System",
    "version": "1.0",
    "category": "Healthcare",
    "author": "Khushi Trivedi",
    "license": "LGPL-3",
    "depends": ["base", "sale", "web", "mail", "account"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/hospital_menu.xml",
        "views/hospital_patient_views.xml",
        "views/hospital_physician_views.xml",
        "views/hospital_specialty_views.xml",
        "data/hospital_treatment_actions.xml",
        "views/hospital_treatment_views.xml",
        "wizard/hospital_treatment_wizard_views.xml",
        "views/sale_order_views.xml",
        "views/account_move_views.xml",
        "views/hospital_diagnosis_views.xml",
        "views/hospital_disease_views.xml",
        "data/hospital_treatment_sequence.xml",
        "report/hospital_treatment_report.xml",
        "report/report_hospital_treatment_template.xml",
        "views/email_templates.xml",
        "views/menu.xml",
        "views/invoice_report_wizard_views.xml",
    ],
    #     "assets": {
    #     "web.assets_backend": [
    #         # "custom_addons/static/src/js/account_payment_popover.js",
    #         "views/account_payment_popover_inherit.xml",
    #     ],
    # },
    "installable": True,
    "application": True,
}
